theme: jekyll-theme-slate
title: Automated Communication & Advocacy 
description: Introduction to Conversational Interface Design
show_downloads: false
twitter_username: includefuntwitterbotaboutbots
email: colemanm@seattleu.edu
