theme: jekyll-theme-slate
title: Automated Communication & Advocacy 
description: Introduction to Conversational Interface Design
name: Miles C. Coleman, PhD
show_downloads: false
github:
  is_project_page: false
