theme: jekyll-theme-slate
title: Automated Communication & Advocacy 
description: Introduction to Conversational Interface Design
name: Miles C. Coleman, PhD
github: false

  
  
  
footer-links:
  email:
  linkedin:
  twitter: funtwitterbot
